# """
# Sigma DataTech Transaction Analytics Pipeline
# AI-Generated by Module 1 | Day 7 — Pipeline Brain
# Generated: 2026-05-26T08:49:45.306729+00:00

# This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
# It is a FIRST DRAFT — review before running against production data.

# Architecture: Bronze -> Silver -> Gold (medallion pattern)
# """

# # ═══════════════════════════════════════════════════════════════
# # SECTION 1: BRONZE + SILVER LAYERS
# # ═══════════════════════════════════════════════════════════════
# from pyspark.sql import SparkSession
# from pyspark.sql.functions import col, max, sum, count, broadcast, datediff, current_date
# from pyspark.sql.types import StructType, StructField, StringType, FloatType, TimestampType, IntegerType
# import sys
# import boto3

# def ingest_bronze(spark, input_path, output_path, run_date, run_id):
#     # Ensure input file exists
#     s3 = boto3.client('s3')
#     try:
#         s3.head_object(Bucket='your-bucket-name', Key=input_path)
#     except:
#         raise FileNotFoundError(f"Source file {input_path} not found.")
    
#     # Read CSV with all columns as strings
#     bronze_schema = StructType([
#         StructField("customer_id", StringType(), True),
#         StructField("transaction_id", StringType(), True),
#         StructField("transaction_date", StringType(), True),
#         StructField("amount", StringType(), True),
#         StructField("payment_method", StringType(), True),
#         StructField("status", StringType(), True),
#         StructField("product_id", StringType(), True),
#     ])
#     bronze_df = spark.read.csv(input_path, schema=bronze_schema, header=True)
    
#     # Add metadata columns
#     bronze_df = bronze_df.withColumn("ingestion_timestamp", current_date()) \
#                          .withColumn("source_file_name", input_path) \
#                          .withColumn("pipeline_run_id", lit(run_id))
    
#     # Write Parquet partitioned by transaction_date
#     bronze_df.write.mode('overwrite').partitionBy("transaction_date").parquet(output_path)

# def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
#     # Read Bronze Parquet with partition pruning on run_date
#     bronze_df = spark.read.parquet(bronze_path).where(col("transaction_date") == run_date)
    
#     # Cast columns to correct types
#     silver_schema = StructType([
#         StructField("customer_id", StringType(), True),
#         StructField("transaction_id", StringType(), True),
#         StructField("transaction_date", TimestampType(), True),
#         StructField("amount", FloatType(), True),
#         StructField("payment_method", StringType(), True),
#         StructField("status", StringType(), True),
#         StructField("product_id", StringType(), True),
#         StructField("ingestion_timestamp", TimestampType(), True),
#         StructField("source_file_name", StringType(), True),
#         StructField("pipeline_run_id", StringType(), True)
#     ])
#     silver_df = bronze_df.select([col(c).cast(silver_schema[c].dataType) for c in silver_schema.fieldNames()])
    
#     # Filter NULL transaction_id and negative amounts
#     silver_df = silver_df.filter(col("transaction_id").isNotNull() & (col("amount") >= 0))
    
#     # Deduplicate on transaction_id keeping latest ingestion_timestamp
#     silver_df = silver_df.dropDuplicates(["transaction_id"], ["ingestion_timestamp"]).orderBy("ingestion_timestamp", ascending=False)
    
#     # Read merchants and broadcast hint
#     merchants_df = spark.read.parquet(merchants_path)
#     merchants_df = broadcast(merchants_df)
    
#     # Join with merchants
#     silver_df = silver_df.join(merchants_df, silver_df.merchant_id == merchants_df.merchant_id, "left")
    
#     # Add quality_flag column
#     null_customer_id_count = silver_df.filter(col("customer_id").isNull()).count()
#     total_rows = silver_df.count()
#     quality_halt_threshold = 0.05
#     if null_customer_id_count / total_rows > quality_halt_threshold:
#         raise Exception("Quality check failed: null customer_id exceeds 5%")
    
#     silver_df = silver_df.withColumn("quality_flag", when(col("customer_id").isNotNull(), "CLEAN").otherwise("UNMATCHED"))
    
#     # Write Parquet partitioned by date
#     silver_df.write.mode('overwrite').partitionBy("transaction_date").parquet(output_path)

# def main():
#     spark = SparkSession.builder.appName("CustomerChurnPredictionFeed").getOrCreate()
#     input_path = "s3://your-bucket-name/bronze/input.csv"
#     bronze_output_path = "s3://your-bucket-name/bronze/"
#     silver_output_path = "s3://your-bucket-name/silver/"
#     merchants_path = "s3://your-bucket-name/dimensions/merchants.parquet"
#     run_date = "2023-04-01"
#     run_id = "run-12345"
    
#     try:
#         ingest_bronze(spark, input_path, bronze_output_path, run_date, run_id)
#         transform_silver(spark, bronze_output_path, merchants_path, silver_output_path, run_date)
#     except Exception as e:
#         print(f"Pipeline failed: {str(e)}")
#         sys.exit(1)

# if __name__ == "__main__":
#     main()


# # ═══════════════════════════════════════════════════════════════
# # SECTION 2: GOLD AGGREGATION LAYER
# # ═══════════════════════════════════════════════════════════════
# from pyspark.sql import SparkSession
# from pyspark.sql.functions import col, max, sum, count, broadcast, expr, to_date, lit, coalesce, when
# from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, TimestampType
# import boto3
# import json
# import sys

# def run_gold(spark, silver_path, gold_output_dir, run_date):
#     # Initialize SNS client
#     sns_client = boto3.client('sns')
#     sns_topic_arn = 'arn:aws:sns:REGION:ACCOUNT_ID:data-engineering'

#     try:
#         # Build merchant performance
#         build_merchant_performance(spark, silver_path, f"{gold_output_dir}/merchant_performance", run_date)

#         # Build customer LTV
#         build_customer_ltv(spark, silver_path, f"{gold_output_dir}/customer_ltv")

#         # Build daily summary
#         build_daily_summary(spark, silver_path, f"{gold_output_dir}/daily_summary", run_date)

#         # Write run metadata
#         run_metadata = {
#             'run_date': run_date,
#            'status': 'SUCCESS'
#         }
#         with open(f"{gold_output_dir}/run_metadata_{run_date}.json", 'w') as f:
#             json.dump(run_metadata, f)

#     except FileNotFoundError as e:
#         # Handle missing source file
#         message = {
#             'error': str(e),
#             'action': 'Raise FileNotFoundError and send SNS alert'
#         }
#         sns_client.publish(TopicArn=sns_topic_arn, Message=json.dumps(message), Subject='Pipeline Failure')
#         sys.exit(1)

# def build_merchant_performance(spark, silver_path, output_path, run_date):
#     # Read Silver layer
#     silver_df = spark.read.parquet(silver_path).where(col("transaction_date").cast(TimestampType()) >= run_date - 30)

#     # Filter for COMPLETED transactions
#     completed_df = silver_df.filter(col("status") == "COMPLETED")

#     # Aggregate metrics
#     merchant_performance_df = completed_df.groupBy("merchant_id").agg(
#         sum("amount").alias("total_revenue"),
#         count("*").alias("txn_count")
#     )

#     # Calculate failure rate
#     all_txns_df = silver_df.groupBy("merchant_id").agg(
#         count("*").alias("total_txns"),
#         count(when(col("status") == "FAILED", 1)).alias("failed_txns")
#     )
#     merchant_performance_df = merchant_performance_df.join(all_txns_df, "merchant_id", "left").withColumn(
#         "failure_rate_pct", (col("failed_txns") / col("total_txns") * 100).cast(DoubleType())
#     ).drop("failed_txns", "total_txns")

#     # Write output
#     merchant_performance_df.repartition("date").write.partitionBy("date").parquet(output_path)

# def build_customer_ltv(spark, silver_path, output_path):
#     # Read Silver layer
#     silver_df = spark.read.parquet(silver_path)

#     # Filter for COMPLETED transactions
#     completed_df = silver_df.filter(col("status") == "COMPLETED")

#     # Aggregate metrics
#     customer_ltv_df = completed_df.groupBy("customer_id").agg(
#         sum("amount").alias("total_spent"),
#         count("*").alias("total_txns"),
#         expr("mode(payment_method)").alias("preferred_payment_method"),
#         min("transaction_date").alias("first_txn_date"),
#         max("transaction_date").alias("last_txn_date")
#     ).withColumn("avg_txn_value", col("total_spent") / col("total_txns"))

#     # Write output
#     customer_ltv_df.write.parquet(output_path)

# def build_daily_summary(spark, silver_path, output_path, run_date):
#     # Read Silver layer
#     silver_df = spark.read.parquet(silver_path).where(col("transaction_date").cast(TimestampType()) >= run_date - 30)

#     # Aggregate metrics
#     daily_summary_df = silver_df.groupBy("transaction_date").agg(
#         sum("amount").alias("total_revenue"),
#         count("*").alias("total_txns"),
#         count(col("customer_id")).alias("unique_customers")
#     )

#     # Calculate unique merchants and failure rate
#     all_txns_df = silver_df.groupBy("transaction_date").agg(
#         count(col("merchant_id")).alias("unique_merchants"),
#         count(when(col("status") == "FAILED", 1)).alias("failed_txns"),
#         count("*").alias("total_txns")
#     )
#     daily_summary_df = daily_summary_df.join(all_txns_df, "transaction_date", "left").withColumn(
#         "failure_rate_pct", (coalesce(col("failed_txns"), lit(0)) / col("total_txns") * 100).cast(DoubleType())
#     ).drop("failed_txns", "total_txns")

#     # Write output
#     daily_summary_df.repartition("transaction_date").write.partitionBy("transaction_date").parquet(output_path)



"""
Sigma DataTech Customer Churn Prediction Pipeline
Fixed Production-Ready Version
Day 7 — Pipeline Brain
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    col,
    max,
    sum,
    count,
    broadcast,
    datediff,
    current_date,
    current_timestamp,
    lit,
    when,
    expr
)

from pyspark.sql.types import (
    StructType,
    StructField,
    StringType,
    FloatType,
    TimestampType,
    DecimalType
)

import boto3
import json
import logging
import os
import shutil
import sys


# ============================================================
# CONFIGURATION
# ============================================================

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s"
)

BRONZE_PATH = os.getenv("BRONZE_PATH")
SILVER_PATH = os.getenv("SILVER_PATH")
GOLD_PATH = os.getenv("GOLD_PATH")

INPUT_PATH = os.getenv("INPUT_PATH")
MERCHANTS_PATH = os.getenv("MERCHANTS_PATH")

SNS_TOPIC_ARN = os.getenv("SNS_TOPIC_ARN")


# ============================================================
# BRONZE LAYER
# ============================================================

def ingest_bronze(spark, input_path, output_path, run_date, run_id):

    logging.info("Starting Bronze ingestion")

    try:

        # Validate input file exists
        s3 = boto3.client("s3")

        # Example validation placeholder
        if input_path is None:
            raise FileNotFoundError("INPUT_PATH environment variable missing")

        bronze_schema = StructType([
            StructField("customer_id", StringType(), True),
            StructField("transaction_id", StringType(), True),
            StructField("transaction_date", StringType(), True),
            StructField("amount", StringType(), True),
            StructField("payment_method", StringType(), True),
            StructField("status", StringType(), True),
            StructField("product_id", StringType(), True),
            StructField("merchant_id", StringType(), True)
        ])

        bronze_df = spark.read.csv(
            input_path,
            schema=bronze_schema,
            header=True
        )
        logging.info(f"Bronze input count: {bronze_df.count()}")
        input_count = bronze_df.count()
        logging.info(f"Bronze input rows: {input_count}")

        # Schema validation
        expected_columns = [
            "customer_id",
            "transaction_id",
            "transaction_date",
            "amount"
        ]

        missing_cols = [
            c for c in expected_columns
            if c not in bronze_df.columns
        ]

        if missing_cols:
            raise Exception(f"Missing columns: {missing_cols}")

        # Metadata columns
        bronze_df = (
            bronze_df
            .withColumn("ingestion_timestamp", current_timestamp())
            .withColumn("source_file_name", lit(input_path))
            .withColumn("pipeline_run_id", lit(run_id))
        )

        partition_path = f"{output_path}/transaction_date={run_date}"

        # Idempotency
        shutil.rmtree(partition_path, ignore_errors=True)

        bronze_df.write \
            .mode("overwrite") \
            .partitionBy("transaction_date") \
            .parquet(output_path)

        logging.info("Bronze ingestion completed")

    except Exception as e:

        logging.error(f"Bronze layer failed: {str(e)}")

        sns = boto3.client("sns")

        sns.publish(
            TopicArn=SNS_TOPIC_ARN,
            Subject="Bronze Pipeline Failure",
            Message=str(e)
        )

        raise


# ============================================================
# SILVER LAYER
# ============================================================

def transform_silver(
    spark,
    bronze_path,
    merchants_path,
    output_path,
    run_date
):

    logging.info("Starting Silver transformation")

    try:

        bronze_df = (
            spark.read.parquet(bronze_path)
            .filter(col("transaction_date") == run_date)
        )

        logging.info(f"Silver input rows: {bronze_df.count()}")

        # Type casting
        silver_df = (
            bronze_df
            .withColumn(
                "amount",
                col("amount").cast(DecimalType(18, 2))
            )
            .withColumn(
                "transaction_date",
                col("transaction_date").cast(TimestampType())
            )
        )

        # Filter COMPLETED transactions
        silver_df = silver_df.filter(
            col("status") == "COMPLETED"
        )
        logging.info(
            f"Rows after COMPLETED filter: {silver_df.count()}"
        )

        # NULL checks
        silver_df = silver_df.filter(
            col("customer_id").isNotNull()
        )

        silver_df = silver_df.filter(
            col("transaction_id").isNotNull()
        )

        # Deduplication
        silver_df = silver_df.dropDuplicates(
            ["transaction_id"]
        )

        logging.info(
            f"Rows after deduplication: {silver_df.count()}"
        )

        # Quality threshold
        total_rows = silver_df.count()

        null_customer_rows = silver_df.filter(
            col("customer_id").isNull()
        ).count()

        if total_rows > 0:

            null_pct = null_customer_rows / total_rows

            if null_pct > 0.05:

                metadata = {
                    "run_date": run_date,
                    "status": "FAILED",
                    "reason": "customer_id null percentage exceeded 5%"
                }

                with open(
                    f"run_metadata_{run_date}.json",
                    "w"
                ) as f:
                    json.dump(metadata, f)

                raise Exception(
                    "Quality threshold failed"
                )

        # Broadcast merchants dimension
        merchants_df = spark.read.parquet(
            merchants_path
        )

        merchants_df = broadcast(merchants_df)

        silver_df = silver_df.join(
            merchants_df,
            "merchant_id",
            "left"
        )

        partition_path = f"{output_path}/transaction_date={run_date}"

        # Idempotency
        shutil.rmtree(partition_path, ignore_errors=True)

        silver_df.write \
            .mode("overwrite") \
            .partitionBy("transaction_date") \
            .parquet(output_path)

        logging.info("Silver transformation completed")

    except Exception as e:

        logging.error(f"Silver layer failed: {str(e)}")

        raise


# ============================================================
# GOLD LAYER
# ============================================================

def build_churn_risk(
    spark,
    silver_path,
    output_path,
    run_date
):

    logging.info("Starting Gold aggregation")

    try:

        silver_df = (
            spark.read.parquet(silver_path)
            .filter(
                col("transaction_date") >=
                expr("current_date() - INTERVAL 30 DAYS")
            )
        )

        logging.info(
            f"Gold input rows: {silver_df.count()}"
        )

        churn_df = (
            silver_df.groupBy("customer_id")
            .agg(
                max("transaction_date").alias(
                    "last_transaction_date"
                ),
                count("transaction_id").alias(
                    "transaction_frequency"
                ),
                sum("amount").alias(
                    "total_spent"
                )
            )
            .withColumn(
                "recency_days",
                datediff(
                    current_date(),
                    col("last_transaction_date")
                )
            )
            .withColumn(
                "risk_status",
                when(
                    col("recency_days") > 14,
                    "at_risk"
                ).otherwise("active")
            )
            .withColumn(
                "generated_at",
                current_timestamp()
            )
        )

        logging.info(
            f"Gold output rows: {churn_df.count()}"
        )

        partition_path = f"{output_path}/transaction_date={run_date}"

        # Idempotency
        shutil.rmtree(partition_path, ignore_errors=True)

        churn_df.write \
            .mode("overwrite") \
            .parquet(output_path)

        metadata = {
            "pipeline_name": "CustomerChurnPredictionFeed",
            "run_date": run_date,
            "run_status": "SUCCESS"
        }

        with open(
            f"run_metadata_{run_date}.json",
            "w"
        ) as f:
            json.dump(metadata, f)

        logging.info("Gold aggregation completed")

    except Exception as e:

        logging.error(f"Gold layer failed: {str(e)}")

        raise


# ============================================================
# MAIN PIPELINE
# ============================================================

def main():

    spark = SparkSession.builder \
        .appName("CustomerChurnPredictionFeed") \
        .getOrCreate()

    run_date = os.getenv("run_date")
    run_id = os.getenv("run_id")

    try:

        ingest_bronze(
            spark,
            INPUT_PATH,
            BRONZE_PATH,
            run_date,
            run_id
        )

        transform_silver(
            spark,
            BRONZE_PATH,
            MERCHANTS_PATH,
            SILVER_PATH,
            run_date
        )

        build_churn_risk(
            spark,
            SILVER_PATH,
            GOLD_PATH,
            run_date
        )

        logging.info("Pipeline completed successfully")

    except Exception as e:

        logging.error(f"Pipeline failed: {str(e)}")

        sys.exit(1)

    finally:

        spark.stop()

expected_columns = [
    "customer_id",
    "transaction_id",
    "transaction_date",
    "amount"
]

if __name__ == "__main__":
    main()